server:
  port: 8088

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

spring:
  security:
    jwt:
      header: Authorization
      secret: ${JWT_SECRET}
      token-validity-in-milliseconds: 10800000 #3시간

  datasource:
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&dialect=org.hibernate.dialect.MariaDBDialect
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      dialect: org.hibernate.dialect.MariaDBDialect
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
#        show_sql: true #show sql
  resources:
    static-locations: file:${FILE_PATH}

springdoc:
  packages-to-scan: com.project.LimeRMS.controller
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

filesPath:
  root: ${FILE_PATH}
  profile: ${FILE_PATH}profile
  board: ${FILE_PATH}board
  content: ${FILE_PATH}content
